spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: Order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root # Replace with your PostgreSQL username
    password:  root # Replace with your PostgreSQL password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use 'validate', 'update', 'create', or 'create-drop' as needed
    show-sql: true # Show SQL queries in the logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8084 # Replace with your preferred port


