spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://pg-1c352440-minaouimh-855e.f.aivencloud.com:19060/defaultdb
    password: avnadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8081
