spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb+srv://minaoui:minaoui@product.eyqho.mongodb.net/?retryWrites=true&w=majority&appName=Product
      database: Products
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
server:
  port: 8080